### ISSUE TITLE
Adapt selectize with tabler

### ISSUE THREAD

**Issue by wrmk** [freeats/freeats#114]
- [x] incorrect color for text in default option #040A11 (should be #182433)
   ![CleanShot 08 11 2024 at 15-11](https://github.com/user-attachments/assets/8b4a23d2-2e48-4c39-aa20-5064f86b4cf9)

- [x] incorrect color for text in disabled option #040A11 0.5 opacity (should be #182433 0.5 opacity)
- [x] incorrect background color for hovered option #DCE1E7 (should be #6C7A91 0.08 opacity)
- [x] incorrect background color #066FD1 (should be #066FD1 0.04 opacity) and text color #FFFFFF (should be #066FD1) for selected option
- [x] incorrect top&bottom paddings for option 6px (should be 8px)
- [x]  incorrect top&bottom paddings for dropdown menu container (selectize-dropdown-content class) 5px (should be 4px)
- [x]  incorrect border color for dropdown menu container #DCE1E7 (should be #042045 0.1 opacity)
- [x]  incorrect avatar size for recruiter select (position and candidate) 32x32px (should be 20x20px)
- [x] Styles for disabled and readonly should be the same as we changed for Text Input ([fix(style): Returned .text-input-component-disabled style](https://github.com/freeats/freeats/pull/85#top))
- [x] Try to apply for Tabler’s badges (tags) for multiple selects

**Comment by wrmk** [comment]
@amgalanbadmaev may i ask you to clarify
- Dropdown menu sizes differs (Recruiter, placement search)
- Try to apply for Tabler’s badges (tags) for multiple selects

**Comment by amgalanbadmaev** [comment]
- Previously dropdown menu sizes differed, meaning that we had different font-sizes in and paddings in them. Now seems to be OK
- Pill select (i.e. Location and previously was Watchers for tasks) uses badges/tags with styles that doesn't match Tabler's default badge (2nd screenshot), related issue: https://github.com/freeats/freeats/issues/16

![CleanShot 11 11 2024 at 16-36](https://github.com/user-attachments/assets/085b920d-3d6c-4148-9447-83b86d2ee5e4)

![CleanShot 11 11 2024 at 16-39](https://github.com/user-attachments/assets/9c8c3113-c44a-40a3-9324-11814780cb7b)

**Comment by wrmk** [comment]
> * Previously dropdown menu sizes differed, meaning that we had different font-sizes in and paddings in them. Now seems to be OK
>   
>   * Note that avatar size for people in Assignee select should also be changed to 20x20px (currently 32x32px)
> * Pill select (i.e. Location and previously was Watchers for tasks) uses badges/tags with styles that doesn't match Tabler's default badge (2nd screenshot), related issue: [Change badges border color #16](https://github.com/freeats/freeats/issues/16)
> 

ok, removed "Dropdown menu sizes differs (Recruiter, placement search)"

avatar for assignee already fixed [here](https://github.com/freeats/freeats/pull/116) and merged into `migration-to-tabler` branch

looking into badges

**Comment by wrmk** [comment]
moved checkpoints for quick search select input [into separate issue](https://github.com/freeats/freeats/issues/129)

**Comment by amgalanbadmaev** [comment]
- incorrect text color for disabled option in dropdown menu (white), should be #040A11 0.5 opacity

![CleanShot 13 11 2024 at 14-01](https://github.com/user-attachments/assets/78db6a3c-de48-4ca2-ae49-967bcf38dc20)

**Comment by amgalanbadmaev** [comment]
> @amgalanbadmaev need to clarify previously we have "incorrect color for text in disabled option #040A11 0.5 opacity (should be #182433 0.5 opacity)" currently we need "incorrect text color for disabled option in dropdown menu (white), should be #040A11 0.5 opacity (high priority)"
> 
> what color for disabled option is correct for us? #040A11 or #182433

Sorry, #182433, mistakenly copy-pasted wrong hex
